redis:
  #Matser的ip地址
  hostName: 10.8.9.92
  #端口号
  port: 6382
  #密码
  password: 123456
  #客户端超时时间单位是毫秒 默认是2000
  timeout: 10000
  #数据库
  database: 2

  #最大空闲数
  maxIdle: 300
  #控制一个pool可分配多少个jedis实例,用来替换redis.maxActive,如果是jedis 2.4以后用该属性
  maxTotal: 1000
  #连接的最小空闲时间 默认1800000毫秒(30分钟)
  minEvictableIdleTimeMillis: 300000
  #每次释放连接的最大数目,默认3
  numTestsPerEvictionRun: 1024
  #逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程, 默认-1
  timeBetweenEvictionRunsMillis: 30000
  #是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
  testOnBorrow: true
  #在空闲时检查有效性, 默认false
  testWhileIdle: true