server:
  port: 8090

## mqtt configuration
mqtt:
  host: tcp://192.168.120.140:1883
  clientId: client
  userName: admin
  password: public
  timeout: 10
  keepalive: 20
  cleanSession: false
  reconnect: true
